# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df081858633caa8128a4b1f8b21ec27bb4fa5ee32815eac73e7c5b10ea6a9a63279d898b4edee7a1b680b67aab933a156e11aac0aa8e45d9e5b98fadaff91231

test:
  secret_key_base: 48b781f47de476ee066b99af8ec12d84fa73647963c186684e154d7c4cfd5060ae3b11e62d44e7ae99aea23d2c0815b894dcc93084f9cfd800307e82343969d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
